#coding=utf8
all_sub_channels = [
    {
        "id": 1,
        "cid": 97,
        "image_type": "vertical",
        "state": 1,
        "position": 0,
        "title": u"韩剧",
        "filter": u"area:韩国|tv_genre:|releaseyear:",
    },
    {
        "id": 2,
        "cid": 97,
        "image_type": "vertical",
        "state": 1,
        "position": 1,
        "title": u"美剧",
        "filter": u"area:美国|tv_genre:|releaseyear:",
    },
    {
        "id": 3,
        "cid": 97,
        "image_type": "vertical",
        "state": 1,
        "position": 2,
        "title": u"大陆剧",
        "filter": u"area:大陆|tv_genre:|releaseyear:",
    },
    {
        "id": 4,
        "cid": 96,
        "image_type": "vertical",
        "state": 1,
        "position": 0,
        "title": u"好莱坞",
        "filter": u"area:美国|movie_genre:|releaseyear:",
    },
    {
        "id": 5,
        "cid": 96,
        "image_type": "vertical",
        "state": 1,
        "position": 2,
        "title": u"韩国",
        "filter": u"area:韩国|movie_genre:|releaseyear:",
    },
    {
        "id": 6,
        "cid": 91,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"社会",
        "filter": u"genre:社会资讯|period:",
    },
    {
        "id": 7,
        "cid": 91,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"科技",
        "filter": u"genre:科技资讯|period:",
    },
    {
        "id": 8,
        "cid": 91,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"生活",
        "filter": u"genre:生活资讯|period:",
    },
    {
        "id": 9,
        "cid": 97,
        "image_type": "vertical",
        "state": 1,
        "position": 3,
        "title": u"港剧",
        "filter": u"area:香港|tv_genre:|releaseyear:",
    },
    {
        "id": 10,
        "cid": 97,
        "image_type": "vertical",
        "state": 1,
        "position": 4,
        "title": u"台剧",
        "filter": u"area:台湾|tv_genre:|releaseyear:",
    },
    {
        "id": 11,
        "cid": 97,
        "image_type": "vertical",
        "state": 1,
        "position": 5,
        "title": u"英剧",
        "filter": u"area:英国|tv_genre:|releaseyear:",
    },
    {
        "id": 12,
        "cid": 95,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"大陆",
        "filter": u"area:大陆|mv_genre:|releaseyear:",
    },
    {
        "id": 13,
        "cid": 95,
        "image_type": "horizontal",
        "state": 1,
        "position": 2,
        "title": u"欧美",
        "filter": u"area:美国,英国,德国,意大利,瑞典,加拿大,法国,芬兰,丹麦,希腊,爱尔兰,荷兰,波兰,俄罗斯,挪威,罗马尼亚,奥地利,苏格兰,瑞典,瑞士,冰岛,葡萄牙,匈牙利|mv_genre:|releaseyear:",
    },
    {
        "id": 14,
        "cid": 95,
        "image_type": "horizontal",
        "state": 1,
        "position": 1,
        "title": u"港台",
        "filter": u"area:香港,台湾|mv_genre:|releaseyear:",
    },
    {
        "id": 15,
        "cid": 95,
        "image_type": "horizontal",
        "state": 1,
        "position": 3,
        "title": u"日韩",
        "filter": u"area:日本,韩国|mv_genre:|releaseyear:",
    },
    {
        "id": 16,
        "cid": 87,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"公开课",
        "filter": u"edu_genre:公开课|distributor:",
    },
    {
        "id": 17,
        "cid": 87,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"TED",
        "filter": u"edu_genre:|distributor:TED",
    },
    {
        "id": 18,
        "cid": 87,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"语言学习",
        "filter": u"edu_genre:外语|distributor:",
    },
    {
        "id": 19,
        "cid": 84,
        "image_type": "horizontal",
        "state": 0,
        "position": 4,
        "title": u"BBC",
        "filter": u"doc_genre:|production:BBC",
    },
    {
        "id": 20,
        "cid": 84,
        "image_type": "horizontal",
        "state": 0,
        "position": 0,
        "title": u"铁血军事",
        "filter": u"doc_genre:军事|production:",
    },
    {
        "id": 21,
        "cid": 84,
        "image_type": "horizontal",
        "state": 0,
        "position": 1,
        "title": u"风云历史",
        "filter": u"doc_genre:历史|production:",
    },
    {
        "id": 22,
        "cid": 84,
        "image_type": "horizontal",
        "state": 0,
        "position": 2,
        "title": u"自然探索",
        "filter": u"doc_genre:自然|production:",
    },
    {
        "id": 23,
        "cid": 84,
        "image_type": "horizontal",
        "state": 0,
        "position": 3,
        "title": u"社会人文",
        "filter": u"doc_genre:社会|production:",
    },
    {
        "id": 24,
        "cid": 98,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"体育资讯",
        "filter": u"genre:体育资讯|period:today",
    },
    {
        "id": 25,
        "cid": 98,
        "image_type": "horizontal",
        "state": 1,
        "position": 3,
        "title": u"格斗",
        "filter": u"genre:格斗|period:today",
    },
    {
        "id": 26,
        "cid": 98,
        "image_type": "horizontal",
        "state": 1,
        "position": 1,
        "title": u"足球",
        "filter": u"genre:足球|period:",
    },
    {
        "id": 27,
        "cid": 98,
        "image_type": "horizontal",
        "state": 1,
        "position": 2,
        "title": u"篮球",
        "filter": u"genre:篮球|period:",
    },
    {
        "id": 28,
        "cid": 98,
        "image_type": "horizontal",
        "state": 1,
        "position": 4,
        "title": u"极限运动",
        "filter": u"genre:极限运动|period:",
    },
    {
        "id": 29,
        "cid": 104,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"新车资讯",
        "filter": u"genre:车讯|period:",
    },
    {
        "id": 30,
        "cid": 104,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"试驾评测",
        "filter": u"genre:试驾|period:",
    },
    {
        "id": 31,
        "cid": 104,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"赛车",
        "filter": u"genre:赛车|period:",
    },
    {
        "id": 32,
        "cid": 104,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"香车美女",
        "filter": u"genre:车女郎|period:",
    },
    {
        "id": 33,
        "cid": 104,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"玩车改装",
        "filter": u"genre:改装|period:",
    },
    {
        "id": 34,
        "cid": 98,
        "image_type": "horizontal",
        "state": 1,
        "position": 5,
        "title": u"跑酷",
        "filter": u"genre:跑酷|period:",
    },
    {
        "id": 35,
        "cid": 105,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"手机",
        "filter": u"genre:手机|period:today",
    },
    {
        "id": 36,
        "cid": 105,
        "image_type": "horizontal",
        "state": 1,
        "position": 2,
        "title": u"DC/DV",
        "filter": u"genre:DC/DV|period:",
    },
    {
        "id": 37,
        "cid": 105,
        "image_type": "horizontal",
        "state": 1,
        "position": 3,
        "title": u"笔记本",
        "filter": u"genre:笔记本|period:",
    },
    {
        "id": 38,
        "cid": 105,
        "image_type": "horizontal",
        "state": 1,
        "position": 4,
        "title": u"游戏机",
        "filter": u"genre:游戏机|period:",
    },
    {
        "id": 39,
        "cid": 105,
        "image_type": "horizontal",
        "state": 1,
        "position": 5,
        "title": u"IT业界",
        "filter": u"genre:IT|period:",
    },
    {
        "id": 40,
        "cid": 105,
        "image_type": "horizontal",
        "state": 1,
        "position": 1,
        "title": u"数码",
        "filter": u"genre:数码|period:",
    },
    {
        "id": 41,
        "cid": 99,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"游戏资讯",
        "filter": u"genre:游戏资讯|period:today",
    },
    {
        "id": 42,
        "cid": 99,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"手机游戏",
        "filter": u"genre:手机游戏|period:",
    },
    {
        "id": 43,
        "cid": 99,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"魔兽世界",
        "filter": u"genre:魔兽世界|period:",
    },
    {
        "id": 44,
        "cid": 99,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"热门网游",
        "filter": u"genre:网络游戏|period:",
    },
    {
        "id": 45,
        "cid": 103,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"幸福厨房",
        "filter": u"genre:美食|period:",
    },
    {
        "id": 46,
        "cid": 103,
        "image_type": "horizontal",
        "state": 1,
        "position": 1,
        "title": u"我爱我宠",
        "filter": u"genre:宠物|period:",
    },
    {
        "id": 47,
        "cid": 103,
        "image_type": "horizontal",
        "state": 1,
        "position": 3,
        "title": u"品味家居",
        "filter": u"genre:家居|period:",
    },
    {
        "id": 48,
        "cid": 103,
        "image_type": "horizontal",
        "state": 1,
        "position": 2,
        "title": u"健康教室",
        "filter": u"genre:健康|period:",
    },
    {
        "id": 49,
        "cid": 89,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"美容",
        "filter": u"genre:美容|period:",
    },
    {
        "id": 50,
        "cid": 89,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"服饰",
        "filter": u"genre:服装服饰|period:",
    },
    {
        "id": 51,
        "cid": 89,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"潮人",
        "filter": u"genre:潮人|period:",
    },
    {
        "id": 52,
        "cid": 88,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"户外运动",
        "filter": u"genre:户外运动|period:",
    },
    {
        "id": 53,
        "cid": 88,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"出境游",
        "filter": u"genre:出境游|period:",
    },
    {
        "id": 54,
        "cid": 88,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"国内游",
        "filter": u"genre:国内游|period:",
    },
    {
        "id": 55,
        "cid": 88,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"攻略指南",
        "filter": u"genre:攻略指南|period:",
    },
    {
        "id": 56,
        "cid": 90,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"宝宝秀",
        "filter": u"genre:宝宝秀|period:",
    },
    {
        "id": 57,
        "cid": 90,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"育儿",
        "filter": u"genre:育儿|period:",
    },
    {
        "id": 58,
        "cid": 90,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"早教",
        "filter": u"genre:早教|period:",
    },
    {
        "id": 59,
        "cid": 90,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"怀孕",
        "filter": u"genre:怀孕|period:",
    },
    {
        "id": 60,
        "cid": 90,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"搞笑儿童",
        "filter": u"genre:搞笑儿童|period:",
    },
    {
        "id": 62,
        "cid": 94,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"欢乐自拍",
        "filter": u"genre:搞笑自拍|period:",
    },
    {
        "id": 63,
        "cid": 94,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"搞笑动物",
        "filter": u"genre:搞笑动物|period:",
    },
    {
        "id": 64,
        "cid": 96,
        "image_type": "vertical",
        "state": 1,
        "position": 1,
        "title": u"香港电影",
        "filter": u"area:香港|movie_genre:|releaseyear:",
    },
    {
        "id": 65,
        "cid": 96,
        "image_type": "vertical",
        "state": 1,
        "position": 3,
        "title": u"大陆",
        "filter": u"area:大陆|movie_genre:|releaseyear:",
    },
    {
        "id": 66,
        "cid": 100,
        "image_type": "vertical",
        "state": 1,
        "position": 1,
        "title": u"日本",
        "filter": u"area:日本|anime_genre:|releaseyear:",
    },
    {
        "id": 67,
        "cid": 100,
        "image_type": "vertical",
        "state": 1,
        "position": 2,
        "title": u"大陆",
        "filter": u"area:大陆|anime_genre:|releaseyear:",
    },
    {
        "id": 68,
        "cid": 100,
        "image_type": "vertical",
        "state": 1,
        "position": 0,
        "title": u"亲子",
        "filter": u"area:|anime_genre:亲子|releaseyear:",
    },
    {
        "id": 69,
        "cid": 100,
        "image_type": "vertical",
        "state": 1,
        "position": 3,
        "title": u"美国",
        "filter": u"area:美国|anime_genre:|releaseyear:",
    },
    {
        "id": 70,
        "cid": 85,
        "image_type": "vertical",
        "state": 1,
        "position": 0,
        "title": u"大陆",
        "filter": u"area:大陆|variety_genre:|releaseyear:",
    },
    {
        "id": 71,
        "cid": 85,
        "image_type": "vertical",
        "state": 1,
        "position": 0,
        "title": u"台湾",
        "filter": u"area:台湾|variety_genre:|releaseyear:",
    },
    {
        "id": 72,
        "cid": 85,
        "image_type": "vertical",
        "state": 1,
        "position": 0,
        "title": u"香港",
        "filter": u"area:香港|variety_genre:|releaseyear:",
    },
    {
        "id": 73,
        "cid": 85,
        "image_type": "vertical",
        "state": 1,
        "position": 0,
        "title": u"韩国",
        "filter": u"area:韩国|variety_genre:|releaseyear:",
    },
    {
        "id": 74,
        "cid": 91,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"时政",
        "filter": u"genre:时政资讯|period:",
    },
    {
        "id": 75,
        "cid": 91,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"军事",
        "filter": u"genre:军事资讯|period:",
    },
    {
        "id": 76,
        "cid": 91,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"财经",
        "filter": u"genre:财经资讯|period:",
    },
    {
        "id": 77,
        "cid": 86,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"娱乐要闻",
        "filter": u"genre:娱乐资讯|period:",
    },
    {
        "id": 78,
        "cid": 86,
        "image_type": "horizontal",
        "state": 1,
        "position": 2,
        "title": u"电视资讯",
        "filter": u"genre:电视资讯|period:",
    },
    {
        "id": 79,
        "cid": 86,
        "image_type": "horizontal",
        "state": 1,
        "position": 1,
        "title": u"电影资讯",
        "filter": u"genre:电影资讯|period:",
    },
    {
        "id": 80,
        "cid": 86,
        "image_type": "horizontal",
        "state": 1,
        "position": 3,
        "title": u"音乐资讯",
        "filter": u"genre:|period:",
    },
    {
        "id": 82,
        "cid": 94,
        "image_type": "horizontal",
        "state": 1,
        "position": 0,
        "title": u"恶搞短片",
        "filter": u"genre:恶搞短片|period:",
    },
]

all_channels = [
    {
        "id": 13,
        "cid": 97,
        "state": 1,
        "position": 0,
        "title": u"电视剧",
    },
    {
        "id": 14,
        "cid": 96,
        "state": 1,
        "position": 1,
        "title": u"电影",
    },
    {
        "id": 15,
        "cid": 100,
        "state": 1,
        "position": 2,
        "title": u"动漫",
    },
    {
        "id": 16,
        "cid": 85,
        "state": 1,
        "position": 3,
        "title": u"综艺",
    },
    {
        "id": 17,
        "cid": 91,
        "state": 1,
        "position": 4,
        "title": u"资讯",
    },
    {
        "id": 18,
        "cid": 86,
        "state": 1,
        "position": 5,
        "title": u"娱乐",
    },
    {
        "id": 19,
        "cid": 1041,
        "state": 0,
        "position": 6,
        "title": u"优酷财经，好看的财经",
    },
    {
        "id": 20,
        "cid": 1519,
        "state": 0,
        "position": 7,
        "title": u"优酷音乐频道",
    },
    {
        "id": 21,
        "cid": 126,
        "state": 0,
        "position": 8,
        "title": u"优酷体育频道 - 优酷视频，提供视频播放，视频发布，视频搜索",
    },
    {
        "id": 22,
        "cid": 904,
        "state": 0,
        "position": 9,
        "title": u"优酷搞笑频道",
    },
    {
        "id": 23,
        "cid": 140,
        "state": 0,
        "position": 10,
        "title": u"优酷音乐频道-无音乐，不生活！",
    },
    {
        "id": 24,
        "cid": 239,
        "state": 0,
        "position": 11,
        "title": u"优酷原创首页",
    },
    {
        "id": 25,
        "cid": 95,
        "state": 1,
        "position": 0,
        "title": u"音乐",
    },
    {
        "id": 26,
        "cid": 87,
        "state": 1,
        "position": 0,
        "title": u"教育",
    },
    {
        "id": 27,
        "cid": 84,
        "state": 1,
        "position": 0,
        "title": u"纪录片",
    },
    {
        "id": 28,
        "cid": 98,
        "state": 1,
        "position": 0,
        "title": u"体育",
    },
    {
        "id": 29,
        "cid": 104,
        "state": 1,
        "position": 0,
        "title": u"汽车",
    },
    {
        "id": 30,
        "cid": 105,
        "state": 1,
        "position": 0,
        "title": u"科技",
    },
    {
        "id": 31,
        "cid": 99,
        "state": 1,
        "position": 0,
        "title": u"游戏",
    },
    {
        "id": 32,
        "cid": 103,
        "state": 1,
        "position": 0,
        "title": u"生活",
    },
    {
        "id": 33,
        "cid": 89,
        "state": 1,
        "position": 0,
        "title": u"时尚",
    },
    {
        "id": 34,
        "cid": 88,
        "state": 1,
        "position": 0,
        "title": u"旅行",
    },
    {
        "id": 35,
        "cid": 90,
        "state": 1,
        "position": 0,
        "title": u"母婴",
    },
    {
        "id": 36,
        "cid": 94,
        "state": 1,
        "position": 0,
        "title": u"搞笑",
    },
]